---
title: "Introduction"
---

This is a dashboard for the [FluSight forecasting challenge](https://github.com/cdcepi/FluSight-forecast-hub/) that is organized by the US CDC.

::: {style='display:flex; align-items: center; justify-content: center'}

[View The Latest Forecasts](forecast.html){.btn .btn-primary role="button"}

:::

The target data for the FluSight challenge is hospitalizations with influenza as reported to the National Healthcare Safety Network (NHSN); this data is publicly available through the CDC's [Weekly Hospital Respiratory Data (HRD) Metrics](https://data.cdc.gov/Public-Health-Surveillance/Weekly-Hospital-Respiratory-Data-HRD-Metrics-by-Ju/mpgq-jmmr/about_data) dataset.

For the evaluations, we have excluded predictions for certain locations or dates due to reporting concerns. Puerto Rico is omitted for the 2024-2025 season due to issues with data instability and backfill, and reference dates 2024-11-23 and 2025-01-25 are removed due to substantial impact from NHSN reporting issues.

Please note that the model performance results shown in this dashboard may not exactly match that of the results in the CDC's end of season short evaluation for FluSight 2024/2025, which additionally removed the following week and location combinations:

- Washington State's forecasts for reference dates 2025-05-17 through 2025 05-31
- Arizona's forecasts for reference date 2025-01-18

::::{.callout-note}

[The CDC notes](https://data.cdc.gov/Public-Health-Surveillance/Weekly-Hospital-Respiratory-Data-HRD-Metrics-by-Ju/mpgq-jmmr/about_data) that:

> Data for reporting dates through April 30, 2024 represent data reported during a previous mandated reporting period as specified by the HHS Secretary. Data for reporting dates May 1, 2024--October 31, 2024 represent voluntarily reported data in the absence of a mandate. Data for reporting dates beginning November 1, 2024 represent data reported during a current mandated reporting period.

::::
